### ISSUE TITLE
DS/ALGO IN JS

### ISSUE THREAD

**Issue by divyanshu-rawat** [divyanshu-rawat/Awesome-JS#62]
Feel free to add data structures written in javascript, feel free to add programs on array, linkedlist, stack, tree, graphs etc.

**Comment by kyle-hall** [comment]
@divyanshu-rawat Would it be okay to open an issue for the specific data structure I want to implement?

**Comment by divyanshu-rawat** [comment]
@kyle-hall great go ahead 👍  Looking forward to it, don't forgot to label Hacktoberfest in the opend issue ;)
